name: Scheduled Supabase DB Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:      # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Resolve IPv4 address of DB host
        id: resolve_ip
        run: |
          IPV4=$(dig +short A ${{ secrets.SUPABASE_DB_HOST }} | head -n1)
          if [ -z "$IPV4" ]; then
            echo "No IPv4 address found for ${{ secrets.SUPABASE_DB_HOST }}"
            exit 1
          fi
          echo "IPV4=$IPV4" >> $GITHUB_OUTPUT

      - name: Test connectivity
        run: |
          ping -c 4 ${{ steps.resolve_ip.outputs.IPV4 }} || echo "Ping failed"
          nc -zv ${{ steps.resolve_ip.outputs.IPV4 }} 5432 || echo "Port 5432 not reachable"

      - name: Dump Supabase PostgreSQL database
        env:
          PGHOST: ${{ steps.resolve_ip.outputs.IPV4 }}
          PGUSER: ${{ secrets.SUPABASE_DB_USER }}
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PGDATABASE: ${{ secrets.SUPABASE_DB_NAME }}
          PGSSLMODE: require
        run: |
          pg_dump --host=$PGHOST --port=5432 --username=$PGUSER --dbname=$PGDATABASE --file=backup.dump --format=custom --no-password

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: supabase-db-backup
          path: backup.dump
