name: Scheduled Supabase DB Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:      # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Dump Supabase PostgreSQL database
        env:
         PGHOST: ${{ secrets.SUPABASE_DB_HOST }}
         PGUSER: ${{ secrets.SUPABASE_DB_USER }}
         PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
         PGDATABASE: ${{ secrets.SUPABASE_DB_NAME }}
         PGSSLMODE: require
        run: |
         pg_dump --host=${{ secrets.SUPABASE_DB_HOST }} --port=5432 --username=${{ secrets.SUPABASE_DB_USER }} --dbname=${{ secrets.SUPABASE_DB_NAME }} --file=backup.dump --format=custom --no-password



      - name: Upload backup artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: supabase-db-backup
          path: backup.dump

